Tests slab pmem multiple keys
pmem/pelikan pull request #37
Opened 2019-07-10 14:34 UTC by kasiawasiuta

Test parametrized with slab memory, item size and number of items. 
Tests fills the slab with n items, deletes and updates items with random keys, checks database consistency after reset and performs modification and check steps again.

2019-07-11 06:07 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @kasiawasiuta)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 4 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUafr8-WvMwlxzLcY4:-LjUafr8-WvMwlxzLcY5:b-yycxe0) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L4)):*
> ```C
> #include <storage/slab/slab.h>
> 
> #include <time/time.h>
> ```

Nit:
Remove this change (removing line)
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 12 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUcYSO1k0YQnRKH1X5:-LjUcYSO1k0YQnRKH1X6:b-p72c7i) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L12)):*
> ```
> #include <stdlib.h>
> ```
remove this
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 19 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUcjjI9MepWLPZEGpx:-LjUcjjI9MepWLPZEGpy:b-6jxk6i) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L19)):*
> ```C
> #define DATAPOOL_PATH "./slab_datapool.pelikan"
> #define UPDATED_VAL "new_val"
> #define INITIAL_N 10000
> ```

Please also be so kind and update commit message to be more descriptive 
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 26 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUbpHCApMu7l47PcTr:-LjUbpHCApMu7l47PcTs:b-eyj1j0) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L26)):*
> ```
> snprintf
> ```
cc_snprintf
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 36 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUbsoC7a31FDhKCZfH:-LjUbsoC7a31FDhKCZfI:b7x9iik) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L36)):*
> ```
> snprint
> ```
cc_snprintf
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 210 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUbYg-CoNTvTCAuW8h:-LjUbYg-CoNTvTCAuW8i:bh9awre) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L210)):*
> ```
> srand((unsigned int)time(0))
> ```
Please remove this randomize part - you could easily perform this removing pattern without it
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 289 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUayb66H2pJXb6Ck_R:-LjUayb66H2pJXb6Ck_S:bk6v02i) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L289)):*
> ```
> for (i = 0; i < slab_nitem ; i++) {
> ```
nit: ( remove space before ; ) same for all loops
> for (i = 0; i < slab_nitem; i++) {
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 302 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUb7-9CsTkdnXr_9Hy:-LjUb7-9CsTkdnXr_9Hz:bembise) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L302)):*
> ```
>   it = item_get(&keys[i]);
> ```
You check here that item was insert and couple of lines your whole set. Please remove one of this checks.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 693 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUakvJ7jWBPIPgdH9s:-LjUakvJ7jWBPIPgdH9t:b-23kn40) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L693)):*
> ```
> #undef NEW_VAL
> #undef KEY
> #undef OLD_VAL
> ```
.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1138 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUanQf6uk6yJXOYSmX:-LjUanQf6uk6yJXOYSmY:b-qtyb6i) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L1138)):*
> ```
> // TODO: Add more parameters
> ```
?


<!-- Sent from Reviewable.io -->

2019-07-12 07:45 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 12 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUcYSO1k0YQnRKH1X5:-LjVBZnQ2Y9aqHyeBF7s:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L12)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include <stdlib.h>
> ```
remove this
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 19 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUcjjI9MepWLPZEGpx:-LjVZl4_D1IpQyA1t7Rl:blrrunw) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L19)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Please also be so kind and update commit message to be more descriptive 
</blockquote></details>

Do you mean commit title? ;) Cause the overall message I find quite descriptive
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 26 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUbpHCApMu7l47PcTr:-LjVBcnW3W0VRjehm3hr:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L26)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> snprintf
> ```
cc_snprintf
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 36 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUbsoC7a31FDhKCZfH:-LjVBeKICBqjqRdILnrI:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L36)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> snprint
> ```
cc_snprintf
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 210 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUbYg-CoNTvTCAuW8h:-LjVC-5fEIhCMcOkOQ0_:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L210)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> srand((unsigned int)time(0))
> ```
Please remove this randomize part - you could easily perform this removing pattern without it
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 289 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUayb66H2pJXb6Ck_R:-LjVCFwz1Y3m0UjmC9XO:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L289)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> for (i = 0; i < slab_nitem ; i++) {
> ```
nit: ( remove space before ; ) same for all loops
> for (i = 0; i < slab_nitem; i++) {
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 302 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUb7-9CsTkdnXr_9Hy:-LjVWA_MDkLtucVqj99z:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L302)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>   it = item_get(&keys[i]);
> ```
You check here that item was insert and couple of lines your whole set. Please remove one of this checks.
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 693 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUakvJ7jWBPIPgdH9s:-LjVWTGt7yklHYALGCDQ:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L693)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #undef NEW_VAL
> #undef KEY
> #undef OLD_VAL
> ```
.
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1138 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUanQf6uk6yJXOYSmX:-Lj_85vVB60yqwMrUtT6:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L1138)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> // TODO: Add more parameters
> ```
?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-12 08:02 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @kasiawasiuta)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 19 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUcjjI9MepWLPZEGpx:-Lj_8NbkBOzmiqDB9fZM:b9ykgyf) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L19)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

Do you mean commit title? ;) Cause the overall message I find quite descriptive
</blockquote></details>

Commit message is "Add parametized tests for pmem" and is not descriptive.
Please be aware that this is a new test - rest one are practically copy of previous implemented test with adding reset part - if it will go to upstream it would be great to be self explained as much as possible if not  - commit message should be helpful
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 248 at r2](https://reviewable.io/reviews/pmem/pelikan/37#-Lj_BhMIAQeyCwRuek3M:-Lj_BhMIAQeyCwRuek3N:b-xvdxud) ([raw file](https://github.com/pmem/pelikan/blob/3ad9745813777cd8d5ea66f7525a2dea66ddfc1f/test/storage/slab_pmem/check_slab_pmem.c#L248)):*
> ```
> val_pattern
> ```
memory leak
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 286 at r2](https://reviewable.io/reviews/pmem/pelikan/37#-Lj_9zWlB710qGI6I4JE:-Lj_9zWlB710qGI6I4JF:b-7lrmid) ([raw file](https://github.com/pmem/pelikan/blob/3ad9745813777cd8d5ea66f7525a2dea66ddfc1f/test/storage/slab_pmem/check_slab_pmem.c#L286)):*
> ```
> * fill database */
> ```
I am not sure but I think this whole part could be simplified like it is done in https://github.com/pmem/pelikan/blob/2808cccecc6eb7c825dc821c5b6bf89242faba62/src/server/twemcache/data/process.c#L52-L61
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1165 at r2](https://reviewable.io/reviews/pmem/pelikan/37#-Lj_9NP9AwkDqre_C7zS:-Lj_9NP9AwkDqre_C7zT:bszppmy) ([raw file](https://github.com/pmem/pelikan/blob/3ad9745813777cd8d5ea66f7525a2dea66ddfc1f/test/storage/slab_pmem/check_slab_pmem.c#L1165)):*
> ```
> 1
> ```
? should be 3
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1172 at r2](https://reviewable.io/reviews/pmem/pelikan/37#-Lj_9JvnDQ-pTMQNLnLe:-Lj_9JvnDQ-pTMQNLnLf:b-pi9d9n) ([raw file](https://github.com/pmem/pelikan/blob/3ad9745813777cd8d5ea66f7525a2dea66ddfc1f/test/storage/slab_pmem/check_slab_pmem.c#L1172)):*
> ```C
>     tcase_add_test(tc_slab, test_evict_lru_basic);
>     tcase_add_test(tc_slab, test_refcount);
>     tcase_add_test(tc_slab, test_evict_refcount);
> ```

remove this
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1175 at r2](https://reviewable.io/reviews/pmem/pelikan/37#-Lj_9Hd93s2Y74AC7oEH:-Lj_9Hd93s2Y74AC7oEI:b-hg64df) ([raw file](https://github.com/pmem/pelikan/blob/3ad9745813777cd8d5ea66f7525a2dea66ddfc1f/test/storage/slab_pmem/check_slab_pmem.c#L1175)):*
> ```
> #undef UPDATED_VAL
> ```
remove this


<!-- Sent from Reviewable.io -->

2019-07-12 08:26 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @kasiawasiuta and @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 19 at r1](https://reviewable.io/reviews/pmem/pelikan/37#-LjUcjjI9MepWLPZEGpx:-Lj_HUZ52FmyjFlKl8F7:btesutw) ([raw file](https://github.com/pmem/pelikan/blob/16fcd3be0c0d9067f7dce7b00b532c5f6da3af30/test/storage/slab_pmem/check_slab_pmem.c#L19)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Commit message is "Add parametized tests for pmem" and is not descriptive.
Please be aware that this is a new test - rest one are practically copy of previous implemented test with adding reset part - if it will go to upstream it would be great to be self explained as much as possible if not  - commit message should be helpful
</blockquote></details>

Please check if the new one is more descriptive
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 248 at r2](https://reviewable.io/reviews/pmem/pelikan/37#-Lj_BhMIAQeyCwRuek3M:-Lj_CaD43zVqbLSeIRjN:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3ad9745813777cd8d5ea66f7525a2dea66ddfc1f/test/storage/slab_pmem/check_slab_pmem.c#L248)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> val_pattern
> ```
memory leak
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1165 at r2](https://reviewable.io/reviews/pmem/pelikan/37#-Lj_9NP9AwkDqre_C7zS:-Lj_CoTj-10iww72Ds2X:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3ad9745813777cd8d5ea66f7525a2dea66ddfc1f/test/storage/slab_pmem/check_slab_pmem.c#L1165)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 1
> ```
? should be 3
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1175 at r2](https://reviewable.io/reviews/pmem/pelikan/37#-Lj_9Hd93s2Y74AC7oEH:-Lj_D--ECS6arthsD2XW:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3ad9745813777cd8d5ea66f7525a2dea66ddfc1f/test/storage/slab_pmem/check_slab_pmem.c#L1175)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #undef UPDATED_VAL
> ```
remove this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-12 09:14 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kasiawasiuta)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 251 at r3](https://reviewable.io/reviews/pmem/pelikan/37#-Lj_Pyp0-89vAw3Cnus1:-Lj_Pyp0-89vAw3Cnus2:bpbysze) ([raw file](https://github.com/pmem/pelikan/blob/0bfc7043769ec17aa87a98e197bb097994d392c6/test/storage/slab_pmem/check_slab_pmem.c#L251)):*
> ```
> if (cc_memcmp(data, val_pattern, sizeof(val_pattern)) != 0) {
> ```
I think you could avoid this val_pattern allocation by use comparison like:

if (data[0] == 'A' && cc_memcmp(data, data + 1, length - 1) == 0)

where length - is data length - the # of A letters


<!-- Sent from Reviewable.io -->

2019-07-12 14:06 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kasiawasiuta and @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 251 at r3](https://reviewable.io/reviews/pmem/pelikan/37#-Lj_Pyp0-89vAw3Cnus1:-Lj_Z61RCyQdQqFZ4Uti:bhnnkfc) ([raw file](https://github.com/pmem/pelikan/blob/0bfc7043769ec17aa87a98e197bb097994d392c6/test/storage/slab_pmem/check_slab_pmem.c#L251)):*
> if (data[0] == 'A' && cc_memcmp(data, data + 1, length - 1) == 0)
I  think it is really good idea and I will apply this change. I dont want to resign from checking if the length is appropriate, so I added the third condition must be added

EDIT: This makes pass currently failing test with the first parameter set. Need to resolve the problem and then think of simplifying this condition


<!-- Sent from Reviewable.io -->

2019-07-15 13:02 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 286 at r2](https://reviewable.io/reviews/pmem/pelikan/37#-Lj_9zWlB710qGI6I4JE:-LjpgxOS4sIQczvXaUiy:bammxt7) ([raw file](https://github.com/pmem/pelikan/blob/3ad9745813777cd8d5ea66f7525a2dea66ddfc1f/test/storage/slab_pmem/check_slab_pmem.c#L286)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> * fill database */
> ```
I am not sure but I think this whole part could be simplified like it is done in https://github.com/pmem/pelikan/blob/2808cccecc6eb7c825dc821c5b6bf89242faba62/src/server/twemcache/data/process.c#L52-L61
</blockquote></details>

Please check my solution, I didnt use static arrays like in this file, but imo the overall concept is implemented.


<!-- Sent from Reviewable.io -->

2019-07-15 13:54 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @kasiawasiuta)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 180 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjptmqJ0r5gS2x20oa8:-LjptmqK2z4-vTFw3yGN:b-y7v1nk) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L180)):*
> ```
>  unsigned long
> ```
why not just uint32_t ?
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 182 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjptvvG2JZ_lKr6zdwN:-LjptvvG2JZ_lKr6zdwO:b-zcfbti) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L182)):*
> ```
>  uint64_t
> ```
uint32_t
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 223 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjptYpK1cYSPhs-LxqA:-LjptYpK1cYSPhs-LxqB:b-9jya7q) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L223)):*
> ```
> data = NULL;
> ```
not needed
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 227 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjpsZCm2qjqtPeVPlqB:-LjpsZCm2qjqtPeVPlqC:b-lfwb91) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L227)):*
> ```
> *d
> ```
i is unsigned
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 229 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjpsistBQ8IRqxSwJFo:-LjpsistBQ8IRqxSwJFp:b-vkawel) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L229)):*
> ```
> sizeof(val_pattern)
> ```
I think you want it to compare more bytes
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 248 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjpqdJh-WXppZkYvQsk:-LjpqdJh-WXppZkYvQsl:b-sa1xhz) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L248)):*
> ```
> struct bstring keys[slab_nitem]
> ```
Variable length array - it works yes but it is not recommended
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1118 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjppcdvCNiKVBSaGlxs:-LjppcdvCNiKVBSaGlxt:b-y2blbc) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L1118)):*
> ```
> 3
> ```
not needed


<!-- Sent from Reviewable.io -->

2019-07-15 14:06 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @kasiawasiuta)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 154 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-Ljpx7yu02Kfuj3nhITH:-Ljpx7yu02Kfuj3nhITI:bysjdzs) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L154)):*
> ```
> uint64_t
> ```
.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 168 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-Ljpx9JE471f3xe28RWA:-Ljpx9JE471f3xe28RWB:bysjdzs) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L168)):*
> ```
> uint64_t
> ```
.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 180 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjpwURF7BNi4zHxxNY5:-LjpwURF7BNi4zHxxNY6:b-mbq7ww) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L180)):*
> ```
> slab_nitem
> ```
it would be more clear to describe this as number of keys, which referred to first parameter
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 189 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjpwjKI2rUNiVqEnE17:-LjpwjKI2rUNiVqEnE18:bbcmpna) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L189)):*
> ```
> if (item_get(keys) == NULL) continue;
> ```
question:
This would be during eviction?


<!-- Sent from Reviewable.io -->

2019-07-16 08:03 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 154 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-Ljpx7yu02Kfuj3nhITH:-Ljthm9D6X20sz4eG5hN:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L154)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> uint64_t
> ```
.
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 168 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-Ljpx9JE471f3xe28RWA:-Ljthl9n9xkatl-dfoT0:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L168)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> uint64_t
> ```
.
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 180 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjptmqJ0r5gS2x20oa8:-Ljthqw49tcztp_VjSAO:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L180)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  unsigned long
> ```
why not just uint32_t ?
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 180 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjpwURF7BNi4zHxxNY5:-LjtidUqAeG8b--N0w5S:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L180)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> slab_nitem
> ```
it would be more clear to describe this as number of keys, which referred to first parameter
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 182 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjptvvG2JZ_lKr6zdwN:-Ljtihr11oE5DhrQAEId:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L182)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  uint64_t
> ```
uint32_t
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 189 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjpwjKI2rUNiVqEnE17:-Ljtisji0evjyMDsNkpe:bu92j68) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L189)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> if (item_get(keys) == NULL) continue;
> ```
question:
This would be during eviction?
</blockquote></details>

When the function is called the second time, some of the keys are already deleted.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 223 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjptYpK1cYSPhs-LxqA:-LjtjEWpAGRimk_sAHET:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L223)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> data = NULL;
> ```
not needed
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 227 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjpsZCm2qjqtPeVPlqB:-LjtjjR3BZbMhynoeZ-q:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L227)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> *d
> ```
i is unsigned
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 229 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjpsistBQ8IRqxSwJFo:-LjtmgiB4kkyHluHqhRM:bfyyzz8) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L229)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> sizeof(val_pattern)
> ```
I think you want it to compare more bytes
</blockquote></details>

Thats rignt!
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 248 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjpqdJh-WXppZkYvQsk:-Ljtkaxm3Ywqucpigx57:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L248)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> struct bstring keys[slab_nitem]
> ```
Variable length array - it works yes but it is not recommended
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1118 at r4](https://reviewable.io/reviews/pmem/pelikan/37#-LjppcdvCNiKVBSaGlxs:-Ljtk2BS9uYjzhRcNWJg:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/b82af72dc295091099c15864e840aea174537619/test/storage/slab_pmem/check_slab_pmem.c#L1118)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 3
> ```
not needed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-16 09:15 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @kasiawasiuta)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 209 at r5](https://reviewable.io/reviews/pmem/pelikan/37#-LjtwgjTAF97dIYaulT7:-LjtwgjTAF97dIYaulT8:bpki7k6) ([raw file](https://github.com/pmem/pelikan/blob/3bdb434e7aa8441b18c2d113e16d33de57b78338/test/storage/slab_pmem/check_slab_pmem.c#L209)):*
> ```
> uint32_t i, deleted_iter = 0, updated_iter = 0;
> ```
remove this since it modified anywhere here
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 247 at r5](https://reviewable.io/reviews/pmem/pelikan/37#-LjtsL6f28ZkrkBcfuuw:-LjtsL6gAM749j4-4weG:b110r4w) ([raw file](https://github.com/pmem/pelikan/blob/3bdb434e7aa8441b18c2d113e16d33de57b78338/test/storage/slab_pmem/check_slab_pmem.c#L247)):*
> ```
> , val
> ```
nit:
To improve readability of this please move this to next line
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1117 at r5](https://reviewable.io/reviews/pmem/pelikan/37#-LjtytgO9wHo4dIze732:-LjtytgO9wHo4dIze733:b2jj7bu) ([raw file](https://github.com/pmem/pelikan/blob/3bdb434e7aa8441b18c2d113e16d33de57b78338/test/storage/slab_pmem/check_slab_pmem.c#L1117)):*
> ```
> struct params p[] = {{ 100*MiB, 50000, KiB}, {100*MiB, 100000, 64}, { 10*MiB, 13, MiB/3 }}
> ```
nit:
please fix formatting: be consistent with spaces after "{"
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1149 at r5](https://reviewable.io/reviews/pmem/pelikan/37#-Ljtt_rOE-H56ci-_CxZ:-Ljtt_rOE-H56ci-_Cx_:b-jetzmw) ([raw file](https://github.com/pmem/pelikan/blob/3bdb434e7aa8441b18c2d113e16d33de57b78338/test/storage/slab_pmem/check_slab_pmem.c#L1149)):*
> ```
> test_crud_multiple_keys
> ```
Nit:
Personally I would create separate tcase for it but it's up to you


<!-- Sent from Reviewable.io -->

2019-07-18 07:45 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 209 at r5](https://reviewable.io/reviews/pmem/pelikan/37#-LjtwgjTAF97dIYaulT7:-Lk-StW2AQe0efQh_iPN:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3bdb434e7aa8441b18c2d113e16d33de57b78338/test/storage/slab_pmem/check_slab_pmem.c#L209)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> uint32_t i, deleted_iter = 0, updated_iter = 0;
> ```
remove this since it modified anywhere here
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 247 at r5](https://reviewable.io/reviews/pmem/pelikan/37#-LjtsL6f28ZkrkBcfuuw:-LjuFxsKAnL260vTO7dj:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3bdb434e7aa8441b18c2d113e16d33de57b78338/test/storage/slab_pmem/check_slab_pmem.c#L247)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> , val
> ```
nit:
To improve readability of this please move this to next line
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1117 at r5](https://reviewable.io/reviews/pmem/pelikan/37#-LjtytgO9wHo4dIze732:-LjuEmj-BETXoGMVV83J:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3bdb434e7aa8441b18c2d113e16d33de57b78338/test/storage/slab_pmem/check_slab_pmem.c#L1117)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> struct params p[] = {{ 100*MiB, 50000, KiB}, {100*MiB, 100000, 64}, { 10*MiB, 13, MiB/3 }}
> ```
nit:
please fix formatting: be consistent with spaces after "{"
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1149 at r5](https://reviewable.io/reviews/pmem/pelikan/37#-Ljtt_rOE-H56ci-_CxZ:-LjuFgr69YZQi1cO65Cv:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/3bdb434e7aa8441b18c2d113e16d33de57b78338/test/storage/slab_pmem/check_slab_pmem.c#L1149)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> test_crud_multiple_keys
> ```
Nit:
Personally I would create separate tcase for it but it's up to you
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-18 08:28 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @kasiawasiuta)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 209 at r5](https://reviewable.io/reviews/pmem/pelikan/37#-LjtwgjTAF97dIYaulT7:-Lk323Zj7z65n5GQL4mr:bv0bwu1) ([raw file](https://github.com/pmem/pelikan/blob/3bdb434e7aa8441b18c2d113e16d33de57b78338/test/storage/slab_pmem/check_slab_pmem.c#L209)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope, you used the solution with static variable
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 208 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk33wvi4vNHDtjXKGcm:-Lk33wvi4vNHDtjXKGcn:bg8dbdc) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L208)):*
> ```
>  /* delete every 6-th element
> ```
Please remove this comment since is not valid anymore
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 210 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk343Jz5_4Cx3NPKO33:-Lk343K-Euq4g-VgkCGJ:b-t6f5dt) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L210)):*
> ```
> if (item_get(&keys[i]) == NULL) continue;
> ```
Please use brackets - see https://github.com/twitter/pelikan/blob/master/docs/coding_style.rst
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 215 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk395nV3EccHhvEPBG4:-Lk395nV3EccHhvEPBG5:b-8zso0r) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L215)):*
> ```
> *(&keys[i]);
> ```
just keys[i]
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 221 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk393py4rz0wvPESnaR:-Lk393pzDrsBaWD2V6h0:b-8zso0r) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L221)):*
> ```
> *(&keys[i]);
> ```
just keys[i]
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 245 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk34WrtEqHWixc5eM63:-Lk34Wru5ZPEzlnkH2ZA:bm5sj5v) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L245)):*
> ```
> item_size - item_ntotal(keys[i].len, 0, 0);
> ```
Question:
Is there a possibility that this will fall over ( item_size will be less than item_ntotal(keys[i].len, 0, 0) ?
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 294 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk34J1rAAVZVNyz9XA9:-Lk34J1rAAVZVNyz9XAA:b-edh6r6) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L294)):*
> ```
>         ck_assert_msg(status == ITEM_OK, "item_reserve not OK - return status %d",
> ```
nit:
This could be easily set in one line
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1351 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk3AJXAAXzhUHItwVq-:-Lk3AJXAAXzhUHItwVq0:b-f16gqf) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L1351)):*
> ```
> struct params p[] = {{100*MiB, 50000, KiB}, {100*MiB, 100000, 64}, {10*MiB, 13, MiB/3}};
> ```
nit:
Have you consider syntax with designated initializers, a little bit of more code but it would easier to read, e.g:

    struct params p[] = {
        {
         .slab_size = 100*MiB,
        .item_number = 50000,
        .item_size = KiB
        },
        {
         .slab_size = 100*MiB,
        .item_number = 100000,
        .item_size = 64
        },
         {
        .slab_size = 10*MiB,
        .item_number = 13,
        .item_size = MiB/3
        }
    };
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1386 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk32CCxCJxdDpKPIMAx:-Lk32CCxCJxdDpKPIMAy:bks3hfw) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L1386)):*
> ```
> /* setting 10 sec timeout for multiple keys testcase */
> ```
nit:
I think function below is self explained.
What you could do is to move this comment above the tc_multiple tcase and explained there that test takes more time than default value provided by Check library
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1387 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk38CP3AmvDBHSCPvu4:-Lk38CP4ErykY7dQRi6F:b-4ppehz) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L1387)):*
> ```
> tcase_set_timeout(tc_multiple, 10);
> ```
please move this before tcase_add_loop_test


<!-- Sent from Reviewable.io -->

2019-07-18 14:04 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @kasiawasiuta and @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 208 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk33wvi4vNHDtjXKGcm:-Lk3BqOD5keQ7yjhmnlt:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L208)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  /* delete every 6-th element
> ```
Please remove this comment since is not valid anymore
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 210 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk343Jz5_4Cx3NPKO33:-Lk3CFDB0w6Xv1qg7b02:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L210)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> if (item_get(&keys[i]) == NULL) continue;
> ```
Please use brackets - see https://github.com/twitter/pelikan/blob/master/docs/coding_style.rst
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 215 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk395nV3EccHhvEPBG4:-Lk3COTQ6hOyGd28KQ2j:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L215)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> *(&keys[i]);
> ```
just keys[i]
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 221 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk393py4rz0wvPESnaR:-Lk4M6t66nGgEn8r5YeA:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L221)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> *(&keys[i]);
> ```
just keys[i]
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 245 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk34WrtEqHWixc5eM63:-Lk3HVPVEIN5fTnXjkD_:b933rxk) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L245)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> item_size - item_ntotal(keys[i].len, 0, 0);
> ```
Question:
Is there a possibility that this will fall over ( item_size will be less than item_ntotal(keys[i].len, 0, 0) ?
</blockquote></details>

There is no such possibility. item_size is sum of key len, val len, header size which is calculated by item_ntotal function. So item_size cannot be bigger than sum of some or all of its ingredients
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 294 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk34J1rAAVZVNyz9XA9:-Lk4N0Tw-ddM6y8wN1-F:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L294)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>         ck_assert_msg(status == ITEM_OK, "item_reserve not OK - return status %d",
> ```
nit:
This could be easily set in one line
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1351 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk3AJXAAXzhUHItwVq-:-Lk4N8Vn4JuTvktChhM9:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L1351)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> struct params p[] = {{100*MiB, 50000, KiB}, {100*MiB, 100000, 64}, {10*MiB, 13, MiB/3}};
> ```
nit:
Have you consider syntax with designated initializers, a little bit of more code but it would easier to read, e.g:

    struct params p[] = {
        {
         .slab_size = 100*MiB,
        .item_number = 50000,
        .item_size = KiB
        },
        {
         .slab_size = 100*MiB,
        .item_number = 100000,
        .item_size = 64
        },
         {
        .slab_size = 10*MiB,
        .item_number = 13,
        .item_size = MiB/3
        }
    };
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1386 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk32CCxCJxdDpKPIMAx:-Lk4NVf02_yj4CyofN9e:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L1386)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> /* setting 10 sec timeout for multiple keys testcase */
> ```
nit:
I think function below is self explained.
What you could do is to move this comment above the tc_multiple tcase and explained there that test takes more time than default value provided by Check library
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1387 at r6](https://reviewable.io/reviews/pmem/pelikan/37#-Lk38CP3AmvDBHSCPvu4:-Lk4NcAt1pk0ubVtFuS6:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/4906ef2d993b831ae83724b9f3f0065e4e2592e5/test/storage/slab_pmem/check_slab_pmem.c#L1387)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> tcase_set_timeout(tc_multiple, 10);
> ```
please move this before tcase_add_loop_test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-07 14:01 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 209 at r5](https://reviewable.io/reviews/pmem/pelikan/37#-LjtwgjTAF97dIYaulT7:-LlgN_ULCzgGWehS_k-f:bph4x6) ([raw file](https://github.com/pmem/pelikan/blob/3bdb434e7aa8441b18c2d113e16d33de57b78338/test/storage/slab_pmem/check_slab_pmem.c#L209)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Nope, you used the solution with static variable
</blockquote></details>

Removed static variables


<!-- Sent from Reviewable.io -->

2019-08-19 12:54 UTC, michalbiesek requested changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @kasiawasiuta and @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 23 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-LmdrhhIBUuAVYtVQUkj:-LmdrhhIBUuAVYtVQUkk:b-1grr6s) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L23)):*
> ```
> #define INITIAL_N 100000
> ```
IMHO this should be removed just allocate appropriate size for nkey.
Now if you want add test for example: 100001 keys you would need to remember to update it.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 25 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-LmdsN3E3S1HaFZaKLAn:-LmdsN3E3S1HaFZaKLAo:b3kre) ([raw file](https://github.com/pmem/pelikan/blob/2ffaa62c3ad036f98fa936ba9bdb883fac8f09bf/test/storage/slab_pmem/check_slab_pmem.c#L25)):*
> ```C
> 
> extern delta_time_i max_ttl;
> ```

?
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 185 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-Lmds-Mz8Btzwer9hsm-:-Lmds-Mz8Btzwer9hsm0:b-krrhb5) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L185)):*
> ```
> static int
> ```
wrong signature - you return true/false
and signature should be rstatus_i (*array_each_fn)(void *, void *);
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 188 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-Lmdu-Df1giW2xBy6Wa_:-Lmdu-Df1giW2xBy6Waa:b-6w6yco) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L188)):*
> ```
> cc_memcmp(((struct bstring *)key1)->data, ((struct bstring *)key2)->data, ((struct bstring *)key1)->len)
> ```
bstring_compare(key1, key2)
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 237 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-LmdvGKID9mP7c6ELV7w:-LmdvGKID9mP7c6ELV7x:b-60tb6v) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L237)):*
> ```
> array_each(keys_deleted, are_keys_equal, &keys[i], &err) < nkey
> ```
nit:
 array_each(keys_deleted, are_keys_equal, &keys[i], &err) != nkey
Could this be done in two line assert and array_each operation it would be easier for read - same apply below
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 251 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-LmdrrGz4LG0FtVfQ-db:-LmdrrGz4LG0FtVfQ-dc:bbp4d47) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L251)):*
> ```
> item_data(it)
> ```
data
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 268 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-LmdsW8m7pvehTcREnJf:-LmdsW8m7pvehTcREnJg:b-aictgk) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L268)):*
> ```
> 100
> ```
could we avoid hardcoding this?
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1413 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-Lmdsyuh4epj-qfxZm5X:-Lmdsyui7tFmx_ArSI_Z:b-5faw02) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L1413)):*
> ```C
>     tcase_add_test(tc_item, test_expire_truncated);
> ```

nit:
one new line would be sufficient 


<!-- Sent from Reviewable.io -->

2019-08-22 06:03 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 23 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-LmdrhhIBUuAVYtVQUkj:-LmruAlLEG49ujNqE-7X:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L23)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #define INITIAL_N 100000
> ```
IMHO this should be removed just allocate appropriate size for nkey.
Now if you want add test for example: 100001 keys you would need to remember to update it.
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 25 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-LmdsN3E3S1HaFZaKLAn:-LmrrBqpBoO01Hw9ZTx5:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/2ffaa62c3ad036f98fa936ba9bdb883fac8f09bf/test/storage/slab_pmem/check_slab_pmem.c#L25)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 185 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-Lmds-Mz8Btzwer9hsm-:-Lmrrq4jBuEgFGDH3Udc:b-30m43i) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L185)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> static int
> ```
wrong signature - you return true/false
and signature should be rstatus_i (*array_each_fn)(void *, void *);
</blockquote></details>

Pls check if it is correct now
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 188 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-Lmdu-Df1giW2xBy6Wa_:-Lmrs2uT0NakkmJKBp8V:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L188)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> cc_memcmp(((struct bstring *)key1)->data, ((struct bstring *)key2)->data, ((struct bstring *)key1)->len)
> ```
bstring_compare(key1, key2)
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 237 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-LmdvGKID9mP7c6ELV7w:-LmrslmYEWOeyjHJral_:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L237)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> array_each(keys_deleted, are_keys_equal, &keys[i], &err) < nkey
> ```
nit:
 array_each(keys_deleted, are_keys_equal, &keys[i], &err) != nkey
Could this be done in two line assert and array_each operation it would be easier for read - same apply below
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 251 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-LmdrrGz4LG0FtVfQ-db:-LmrssqE7yg-tcJx91yz:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L251)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> item_data(it)
> ```
data
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 268 at r8](https://reviewable.io/reviews/pmem/pelikan/37#-LmdsW8m7pvehTcREnJf:-LmrtZjMD3ejL2NZ5e6n:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/eaac3bda6805d2df6499c1c9f07d476f5b3e11e7/test/storage/slab_pmem/check_slab_pmem.c#L268)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 100
> ```
could we avoid hardcoding this?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-22 07:08 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @kasiawasiuta and @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 188 at r9](https://reviewable.io/reviews/pmem/pelikan/37#-LmrvzNL7h6jVOaFRVrR:-LmrvzNM6Idx9jQvfOad:b-r6hksb) ([raw file](https://github.com/pmem/pelikan/blob/9ed957990956cf7761dd59b3616abe4ed1f65289/test/storage/slab_pmem/check_slab_pmem.c#L188)):*
> ```
> bstring_compare(key1, key2)
> ```
you should compare the returned value to 0 - only then this will be equal

please return instead of true 0 and instead of false 1
(0 is CC_OK) but there are no nice status for not ok - CC_ERROR is misleading

In your case this function works but it got reverse logic
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 210 at r9](https://reviewable.io/reviews/pmem/pelikan/37#-Lms8hCH3tIObzUw4gGX:-Lms8hCID5OjRva9b-m2:b-9mgblq) ([raw file](https://github.com/pmem/pelikan/blob/9ed957990956cf7761dd59b3616abe4ed1f65289/test/storage/slab_pmem/check_slab_pmem.c#L210)):*
> ```C
>         if (i % del_idx == 0) {
>             ck_assert_msg(item_delete(&keys[i]),
>                           "item_delete for key %.*s not successful", keys[i].len, keys[i].data);
> ```

nit:
it will fit in one line same for ck_assert_msg below
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 247 at r9](https://reviewable.io/reviews/pmem/pelikan/37#-Lmrw_Hc4bJSaJ7YsWG5:-Lmrw_Hc4bJSaJ7YsWG6:bms5s7r) ([raw file](https://github.com/pmem/pelikan/blob/9ed957990956cf7761dd59b3616abe4ed1f65289/test/storage/slab_pmem/check_slab_pmem.c#L247)):*
> ```
>  ret = array_each(keys_updated, are_keys_equal, &keys[i], &err);
> ```
nit:
indent
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 320 at r9](https://reviewable.io/reviews/pmem/pelikan/37#-LmrwUj94Ck2I1TriupZ:-LmrwUj94Ck2I1Triup_:b3h5hfu) ([raw file](https://github.com/pmem/pelikan/blob/9ed957990956cf7761dd59b3616abe4ed1f65289/test/storage/slab_pmem/check_slab_pmem.c#L320)):*
> ```C
> 
>     array_destroy(&keys_deleted);
>     array_destroy(&keys_updated);
> ```

cc_free(keys)
but as we spoke offline try to use keys structure as array 
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1674 at r9](https://reviewable.io/reviews/pmem/pelikan/37#-Lms17Cw11sYrU6nONFH:-Lms17Cx4MgsALIsQJT4:b5yjxwv) ([raw file](https://github.com/pmem/pelikan/blob/9ed957990956cf7761dd59b3616abe4ed1f65289/test/storage/slab_pmem/check_slab_pmem.c#L1674)):*
> ```
> tcase_set_timeout(tc_multiple, 20)
> ```
on my machine it works without this timeout 


<!-- Sent from Reviewable.io -->

2019-09-03 13:59 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 188 at r9](https://reviewable.io/reviews/pmem/pelikan/37#-LmrvzNL7h6jVOaFRVrR:-Lnq_ved-PxgeTRpWsAJ:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/9ed957990956cf7761dd59b3616abe4ed1f65289/test/storage/slab_pmem/check_slab_pmem.c#L188)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> bstring_compare(key1, key2)
> ```
you should compare the returned value to 0 - only then this will be equal

please return instead of true 0 and instead of false 1
(0 is CC_OK) but there are no nice status for not ok - CC_ERROR is misleading

In your case this function works but it got reverse logic
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 210 at r9](https://reviewable.io/reviews/pmem/pelikan/37#-Lms8hCH3tIObzUw4gGX:-Lnqa8NR0AAI6W2WNjwM:bb6un1j) ([raw file](https://github.com/pmem/pelikan/blob/9ed957990956cf7761dd59b3616abe4ed1f65289/test/storage/slab_pmem/check_slab_pmem.c#L210)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

nit:
it will fit in one line same for ck_assert_msg below
</blockquote></details>

Done
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 247 at r9](https://reviewable.io/reviews/pmem/pelikan/37#-Lmrw_Hc4bJSaJ7YsWG5:-Lnqaj0M1cYDtaRYy2XY:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/9ed957990956cf7761dd59b3616abe4ed1f65289/test/storage/slab_pmem/check_slab_pmem.c#L247)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  ret = array_each(keys_updated, are_keys_equal, &keys[i], &err);
> ```
nit:
indent
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 320 at r9](https://reviewable.io/reviews/pmem/pelikan/37#-LmrwUj94Ck2I1TriupZ:-LnrPL2n4qeqUrNWmkfx:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/9ed957990956cf7761dd59b3616abe4ed1f65289/test/storage/slab_pmem/check_slab_pmem.c#L320)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

cc_free(keys)
but as we spoke offline try to use keys structure as array 
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1674 at r9](https://reviewable.io/reviews/pmem/pelikan/37#-Lms17Cw11sYrU6nONFH:-LnrPYPx6pYAryXrLnP7:bo0a8g) ([raw file](https://github.com/pmem/pelikan/blob/9ed957990956cf7761dd59b3616abe4ed1f65289/test/storage/slab_pmem/check_slab_pmem.c#L1674)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> tcase_set_timeout(tc_multiple, 20)
> ```
on my machine it works without this timeout 
</blockquote></details>

Probably after changing implementation to cc_array on mine it does too.


<!-- Sent from Reviewable.io -->

2019-09-18 13:09 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @kasiawasiuta and @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 203 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnutOvX5xqVIl0nFMFg:-LnutOvYBRyQMrTv3duA:b-ddmz1) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L203)):*
> ```
> keys->nelem
> ```
array_nelem(keys)
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 204 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnutBbQ30Q03Ea5IdwR:-LnutBbQ30Q03Ea5IdwS:bezuqlf) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L204)):*
> ```
> item_get(op_key = array_get(keys, i)))
> ```
split this:
op_key = array_get(keys, i);
if (it = item_get(op_key) == NULL)
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 231 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-Lnut1QpCkcU9JTFwJOD:-Lnut1QpCkcU9JTFwJOE:b-ddmz1) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L231)):*
> ```
> keys->nelem
> ```
array_nelem(keys)
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 232 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnuxPmz-TCZA9Ul-e2R:-LnuxPn0D3ncA7v5KmKm:bq7kxnd) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L232)):*
> ```
> item_get(key = array_get(keys, i));
> ```
split this
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 236 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnutU2Y-GATbOYVlI_S:-LnutU2Y-GATbOYVlI_T:b-ddmz1) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L236)):*
> ```
> keys->nelem
> ```
array_nelem(keys)
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 245 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnutYj93sQSKM9xi73Y:-LnutYjA1hnf1Iilu-sC:b-ddmz1) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L245)):*
> ```
> keys->nelem
> ```
array_nelem(keys)
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 259 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnuvzDi2mgrNTi7-zo8:-LnuvzDi2mgrNTi7-zo9:bclam5p) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L259)):*
> ```
> struct array *keys;
> ```
You define the same type of structure couple lines below.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 298 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnuwQwG170tksDGGsQf:-LnuwQwHACKSZG5ExvgS:b-64qwz3) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L298)):*
> ```
>  it = item_get(key = array_get(keys, i));
> ```
split this
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1694 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnutkzdENWAaWk03ZxH:-LnutkzeBfaU5MtUU5Ot:bxmy4hp) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L1694)):*
> ```
>  srunner_set_fork_status(srunner, CK_NOFORK);
> ```
?


<!-- Sent from Reviewable.io -->

2019-09-18 13:48 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 203 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnutOvX5xqVIl0nFMFg:-Lp3_8yb0Xt3ZiI8ENcQ:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L203)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> keys->nelem
> ```
array_nelem(keys)
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 204 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnutBbQ30Q03Ea5IdwR:-Lp3_WWw8xcs2lBk_7np:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L204)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> item_get(op_key = array_get(keys, i)))
> ```
split this:
op_key = array_get(keys, i);
if (it = item_get(op_key) == NULL)
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 231 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-Lnut1QpCkcU9JTFwJOD:-Lp3_Y-752YsHkRxicAg:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L231)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> keys->nelem
> ```
array_nelem(keys)
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 232 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnuxPmz-TCZA9Ul-e2R:-Lp3_YyO6rPmvSa2u7YH:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L232)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> item_get(key = array_get(keys, i));
> ```
split this
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 236 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnutU2Y-GATbOYVlI_S:-Lp3_ZPg7XO1uLGatZ9c:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L236)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> keys->nelem
> ```
array_nelem(keys)
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 245 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnutYj93sQSKM9xi73Y:-Lp3_lxU-gKrWZKZAmHe:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L245)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> keys->nelem
> ```
array_nelem(keys)
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 259 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnuvzDi2mgrNTi7-zo8:-Lp3_srL9adeq41JiDne:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L259)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> struct array *keys;
> ```
You define the same type of structure couple lines below.
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 298 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnuwQwG170tksDGGsQf:-Lp3a2fO7s-XvEwWRNnT:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L298)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  it = item_get(key = array_get(keys, i));
> ```
split this
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1694 at r10](https://reviewable.io/reviews/pmem/pelikan/37#-LnutkzdENWAaWk03ZxH:-Lp3aGBp8dJQoFgzJx3z:b-hfpv0l) ([raw file](https://github.com/pmem/pelikan/blob/692aa5bb85d90455e7d13c70eaba5eede8463150/test/storage/slab_pmem/check_slab_pmem.c#L1694)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  srunner_set_fork_status(srunner, CK_NOFORK);
> ```
?
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2019-09-25 10:21 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta and @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 371 at r11](https://reviewable.io/reviews/pmem/pelikan/37#-Lpbvw3EDNHdkfkdsogB:-Lpbvw3EDNHdkfkdsogC:bsvjf1e) ([raw file](https://github.com/pmem/pelikan/blob/c483627a819a20c575c5ab3a1a5795378d120cb4/test/storage/slab_pmem/check_slab_pmem.c#L371)):*
> ```C
>     val = str2bstr(VAL);
> 
>     test_reset(1);
> ```

Just to let you know, you could revert this change since it was merge with https://github.com/pmem/pelikan/pull/73


<!-- Sent from Reviewable.io -->

2019-10-03 11:48 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 371 at r11](https://reviewable.io/reviews/pmem/pelikan/37#-Lpbvw3EDNHdkfkdsogB:-LqGRqDx9ulQnnsxGLcZ:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/c483627a819a20c575c5ab3a1a5795378d120cb4/test/storage/slab_pmem/check_slab_pmem.c#L371)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Just to let you know, you could revert this change since it was merge with https://github.com/pmem/pelikan/pull/73
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-03 12:44 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @kasiawasiuta and @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 224 at r12](https://reviewable.io/reviews/pmem/pelikan/37#-LqGdLpO6nmhPbX7cJJE:-LqGdLpP8lFVnS7sIXr3:b-qccygf) ([raw file](https://github.com/pmem/pelikan/blob/5971b1cf40ca1e68ed6036a200bf67d75b5dad1a/test/storage/slab_pmem/check_slab_pmem.c#L224)):*
> ```
> keys
> ```
Please look for compilation status and try to fix Wshadow warning
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 236 at r12](https://reviewable.io/reviews/pmem/pelikan/37#-LqG_ylGDkbapPib0ytr:-LqG_ylHAbuiAYz1qT-p:bmv453a) ([raw file](https://github.com/pmem/pelikan/blob/5971b1cf40ca1e68ed6036a200bf67d75b5dad1a/test/storage/slab_pmem/check_slab_pmem.c#L236)):*
> ```
> (it = item_get(op_key)) == NULL
> ```
nit:
Since you use it in item_update(it, &new_val);, please separate this operation:

it = item_get(op_key)
if (it == NULL )
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 244 at r12](https://reviewable.io/reviews/pmem/pelikan/37#-LqGbk9e8xfB6orJ2oVn:-LqGbk9e8xfB6orJ2oVo:b-jqw5bi) ([raw file](https://github.com/pmem/pelikan/blob/5971b1cf40ca1e68ed6036a200bf67d75b5dad1a/test/storage/slab_pmem/check_slab_pmem.c#L244)):*
> ```
> it != NULL
> ```
I think this will never happen - see if ((it = item_get(op_key)) == NULL) you continue in case of no item is found
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 272 at r12](https://reviewable.io/reviews/pmem/pelikan/37#-LqGca9nCM29wyzj1uKZ:-LqGca9o0YW5PLyX9GiU:b-knrk6x) ([raw file](https://github.com/pmem/pelikan/blob/5971b1cf40ca1e68ed6036a200bf67d75b5dad1a/test/storage/slab_pmem/check_slab_pmem.c#L272)):*
> ```
> cc_memcmp(UPDATED_VAL, data, sizeof(UPDATED_VAL) - 1)
> ```
cc_strncmp(UPDATED_VAL, data, sizeof(UPDATED_VAL) ?
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1721 at r12](https://reviewable.io/reviews/pmem/pelikan/37#-LqG_kY65Qr7Wbafalk2:-LqG_kY65Qr7Wbafalk3:bvywxsm) ([raw file](https://github.com/pmem/pelikan/blob/5971b1cf40ca1e68ed6036a200bf67d75b5dad1a/test/storage/slab_pmem/check_slab_pmem.c#L1721)):*
<details><summary><i alt="summary">Quoted 23 lines of code…</i></summary>

> ```
> //    tcase_add_test(tc_item, test_insert_basic);
> //    tcase_add_test(tc_item, test_insert_large);
> //    tcase_add_test(tc_item, test_reserve_backfill_release);
> //    tcase_add_test(tc_item, test_reserve_backfill_link);
> //    tcase_add_test(tc_item, test_append_basic);
> //    tcase_add_test(tc_item, test_prepend_basic);
> //    tcase_add_test(tc_item, test_annex_sequence);
> //    tcase_add_test(tc_item, test_delete_basic);
> //    tcase_add_test(tc_item, test_update_basic);
> //    tcase_add_test(tc_item, test_flush_basic);
> //    tcase_add_test(tc_item, test_update_basic_after_restart);
> //    tcase_add_test(tc_item, test_expire_basic);
> //    tcase_add_test(tc_item, test_expire_truncated);
> //    tcase_add_test(tc_item, test_freeq);
> //    tcase_add_test(tc_item, test_release_reserved_items_after_restart);
> 
> //    TCase *tc_slab = tcase_create("slab api");
> //    suite_add_tcase(s, tc_slab);
> //    tcase_add_test(tc_slab, test_lruq_rebuild);
> //    tcase_add_test(tc_slab, test_evict_lru_basic);
> //    tcase_add_test(tc_slab, test_refcount);
> //    tcase_add_test(tc_slab, test_evict_refcount);
> //    tcase_add_exit_test(tc_slab, test_setup_wrong_path, EX_CONFIG);
> ```
</details>

:)
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1753 at r12](https://reviewable.io/reviews/pmem/pelikan/37#-LqG_iD34NBAVd2VRAqt:-LqG_iD34NBAVd2VRAqu:byoym9d) ([raw file](https://github.com/pmem/pelikan/blob/5971b1cf40ca1e68ed6036a200bf67d75b5dad1a/test/storage/slab_pmem/check_slab_pmem.c#L1753)):*
> ```
>    srunner_set_fork_status(srunner, CK_NOFORK);
> ```
:)


<!-- Sent from Reviewable.io -->

2019-10-03 13:08 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 224 at r12](https://reviewable.io/reviews/pmem/pelikan/37#-LqGdLpO6nmhPbX7cJJE:-LqGembl8DAtGiucmfvh:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/5971b1cf40ca1e68ed6036a200bf67d75b5dad1a/test/storage/slab_pmem/check_slab_pmem.c#L224)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> keys
> ```
Please look for compilation status and try to fix Wshadow warning
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 244 at r12](https://reviewable.io/reviews/pmem/pelikan/37#-LqGbk9e8xfB6orJ2oVn:-LqGf-AKCjMjUZO_XhQL:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/5971b1cf40ca1e68ed6036a200bf67d75b5dad1a/test/storage/slab_pmem/check_slab_pmem.c#L244)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> it != NULL
> ```
I think this will never happen - see if ((it = item_get(op_key)) == NULL) you continue in case of no item is found
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 272 at r12](https://reviewable.io/reviews/pmem/pelikan/37#-LqGca9nCM29wyzj1uKZ:-LqGj-CsC0AQPzEUbDjO:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/5971b1cf40ca1e68ed6036a200bf67d75b5dad1a/test/storage/slab_pmem/check_slab_pmem.c#L272)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> cc_memcmp(UPDATED_VAL, data, sizeof(UPDATED_VAL) - 1)
> ```
cc_strncmp(UPDATED_VAL, data, sizeof(UPDATED_VAL) ?
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1721 at r12](https://reviewable.io/reviews/pmem/pelikan/37#-LqG_kY65Qr7Wbafalk2:-LqGf0t28k4o8fcTUEyD:bb71m7e) ([raw file](https://github.com/pmem/pelikan/blob/5971b1cf40ca1e68ed6036a200bf67d75b5dad1a/test/storage/slab_pmem/check_slab_pmem.c#L1721)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> //    tcase_add_test(tc_item, test_insert_basic);
> //    tcase_add_test(tc_item, test_insert_large);
> //    tcase_add_test(tc_item, test_reserve_backfill_release);
> //    tcase_add_test(tc_item, test_reserve_backfill_link);
> //    tcase_add_test(tc_item, test_append_basic);
> //    tcase_add_test(tc_item, test_prepend_basic);
> //    tcase_add_test(tc_item, test_annex_sequence);
> //    tcase_add_test(tc_item, test_delete_basic);
> //    tcase_add_test(tc_item, test_update_basic);
> //    tcase_add_test(tc_item, test_flush_basic);
> //    tcase_add_test(tc_item, test_update_basic_after_restart);
> //    tcase_add_test(tc_item, test_expire_basic);
> //    tcase_add_test(tc_item, test_expire_truncated);
> //    tcase_add_test(tc_item, test_freeq);
> //    tcase_add_test(tc_item, test_release_reserved_items_after_restart);
> 
> //    TCase *tc_slab = tcase_create("slab api");
> //    suite_add_tcase(s, tc_slab);
> //    tcase_add_test(tc_slab, test_lruq_rebuild);
> //    tcase_add_test(tc_slab, test_evict_lru_basic);
> //    tcase_add_test(tc_slab, test_refcount);
> //    tcase_add_test(tc_slab, test_evict_refcount);
> //    tcase_add_exit_test(tc_slab, test_setup_wrong_path, EX_CONFIG);
> ```
:)
</blockquote></details>

Omg.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1753 at r12](https://reviewable.io/reviews/pmem/pelikan/37#-LqG_iD34NBAVd2VRAqt:-LqGf1HL-KqqC4lKZWbq:bb71m7e) ([raw file](https://github.com/pmem/pelikan/blob/5971b1cf40ca1e68ed6036a200bf67d75b5dad1a/test/storage/slab_pmem/check_slab_pmem.c#L1753)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>    srunner_set_fork_status(srunner, CK_NOFORK);
> ```
:)
</blockquote></details>

Omg.


<!-- Sent from Reviewable.io -->

2019-10-03 13:30 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta and @michalbiesek)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 272 at r12](https://reviewable.io/reviews/pmem/pelikan/37#-LqGca9nCM29wyzj1uKZ:-LqGmmax-xADDHJniPg6:b-9hvn7t) ([raw file](https://github.com/pmem/pelikan/blob/5971b1cf40ca1e68ed6036a200bf67d75b5dad1a/test/storage/slab_pmem/check_slab_pmem.c#L272)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

Done.
</blockquote></details>

My bad - please restore previous solution


<!-- Sent from Reviewable.io -->

2019-10-04 09:33 UTC, michalbiesek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/37#-:-LqL6TXY3fl_J-deQCdY:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @michalbiesek)



<!-- Sent from Reviewable.io -->

2019-10-04 09:33 UTC, merged