Test check cleaning data after restart
pmem/pelikan pull request #67
Opened 2019-08-08 12:40 UTC by kasiawasiuta

This test check whether items which were only reserved are not allocated after reopening datapool with new mapping.

2019-08-09 11:01 UTC, TomekIdczak97 reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: all files reviewed, 1 unresolved discussion (waiting on @kasiawasiuta)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1264 at r1](https://reviewable.io/reviews/pmem/pelikan/67#-Llq-75MBKRSZCcdo6xv:-Llq-75MBKRSZCcdo6xw:bhc6ifm) ([raw file](https://github.com/pmem/pelikan/blob/7923a08b18bace74061835e7083d11ad45f3917d/test/storage/slab_pmem/check_slab_pmem.c#L1264)):*
> ```C
> END_TEST
> 
> START_TEST(test_release_reserved_items_when_restarting)
> ```

Can you move this test, so it will be between basic pmem tests and slab metrics tests, please? In current form merge with the rest of slab metrics tests could lead to conflicts.


<!-- Sent from Reviewable.io -->

2019-08-19 12:09 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @kasiawasiuta and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 48 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdleOD6ThyIi3dRvEe:-LmdleOD6ThyIi3dRvEf:bmq5zg4) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L48)):*
> ```
> ()
> ```
nit:
replace with (void)
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 51 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlB815pmIMtP4LlXf:-LmdlB815pmIMtP4LlXg:b-wxcrfb) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L51)):*
> ```
>     char *command = cc_zalloc(1000);
>     char *pid = cc_zalloc(10);
> ```
where is this freed?
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 57 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlEetCL_CCqy2R-t2:-LmdlEetCL_CCqy2R-t3:b9984b) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L57)):*
> ```
> fgets(pid, 1024, pf);
> ```
getpid() would do the job ?
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 80 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlHoQAp7eBmSgm6SA:-LmdlHoQAp7eBmSgm6SB:b-a6z8rp) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L80)):*
> ```
> void *rearrange_pool_mapping_addr = NULL;
> ```
> ```
it could be assign directly
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 81 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlQDs49qdnpsUnS28:-LmdlQDs49qdnpsUnS29:bovggsn) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L81)):*
> ```
> rearrange_pool_mapping_addr
> ```
nit:
please do this mmap operation in one line - not need for splitting it
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 83 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlSzU0zCUcXthrDKJ:-LmdlSzU0zCUcXthrDKK:ba6xx0v) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L83)):*
> ```
> (size_t)getpagesize()
> ```
nit:
Could you use more portable solution described in:
http://man7.org/linux/man-pages/man2/getpagesize.2.html
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1286 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-Lmdlniy8frMYYI3ER8w:-Lmdlniy8frMYYI3ER8x:bvdszxg) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L1286)):*
> ```
> 1
> ```
3?
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1357 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-Lmdlv0gCUdMV0dZOQ4N:-Lmdlv0gCUdMV0dZOQ4O:b-gmpiqm) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L1357)):*
> ```
> srunner_set_fork_status(srunner, CK_FORK);
> ```
?


<!-- Sent from Reviewable.io -->

2019-08-19 15:59 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @michalbiesek and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1264 at r1](https://reviewable.io/reviews/pmem/pelikan/67#-Llq-75MBKRSZCcdo6xv:-LmeOfpeAOeuxkdo-VZl:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/7923a08b18bace74061835e7083d11ad45f3917d/test/storage/slab_pmem/check_slab_pmem.c#L1264)):*
<details><summary><i>Previously, TomekIdczak97 wrote…</i></summary><blockquote>

Can you move this test, so it will be between basic pmem tests and slab metrics tests, please? In current form merge with the rest of slab metrics tests could lead to conflicts.
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 48 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdleOD6ThyIi3dRvEe:-LmeNTGbCZcC-MqIiASQ:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L48)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ()
> ```
nit:
replace with (void)
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 51 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlB815pmIMtP4LlXf:-LmeNiF2D8va8BIYjkf6:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L51)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     char *command = cc_zalloc(1000);
>     char *pid = cc_zalloc(10);
> ```
where is this freed?
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 57 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlEetCL_CCqy2R-t2:-LmeZxMU82w_1jDWGc1E:b-5gctlm) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L57)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> fgets(pid, 1024, pf);
> ```
getpid() would do the job ?
</blockquote></details>

It does :)
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 80 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlHoQAp7eBmSgm6SA:-LmeNuINEB6c1lLUInzi:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L80)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> void *rearrange_pool_mapping_addr = NULL;
> ```
> ```
it could be assign directly
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 81 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlQDs49qdnpsUnS28:-LmeNvGdD2qjf_IWKn4l:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L81)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> rearrange_pool_mapping_addr
> ```
nit:
please do this mmap operation in one line - not need for splitting it
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 83 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlSzU0zCUcXthrDKJ:-LmeOAqs1FjtGLl2Cec3:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L83)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> (size_t)getpagesize()
> ```
nit:
Could you use more portable solution described in:
http://man7.org/linux/man-pages/man2/getpagesize.2.html
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1286 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-Lmdlniy8frMYYI3ER8w:-LmeNMRQBxiBgZdMkvsg:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L1286)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 1
> ```
3?
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1357 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-Lmdlv0gCUdMV0dZOQ4N:-LmeN5g4A0wJ81ISD4G8:b-bh11t5) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L1357)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> srunner_set_fork_status(srunner, CK_FORK);
> ```
?
</blockquote></details>

The signal handling functionality only works in CK_FORK mode. 
http://check.sourceforge.net/doc/check_html/check_4.html#Testing-Signal-Handling-and-Exit-Values


<!-- Sent from Reviewable.io -->

2019-08-20 06:26 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @kasiawasiuta and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 51 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlB815pmIMtP4LlXf:-LmhgtP3Ax1QIAxE9HRc:b-k45yoz) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L51)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I am not sure if this allocations is needed you could do this by simple array with constant size.
Regarding the rest of code below I need to think if this could be simplified
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 81 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlQDs49qdnpsUnS28:-LmhfIsf-O2--0YPGK2v:bb710yj) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L81)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 83 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlSzU0zCUcXthrDKJ:-LmhfNRu2QAmLTwwme1A:b-8d93xe) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L83)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

Done.
</blockquote></details>

please use local variable for that since you call it sysconf here twice
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1357 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-Lmdlv0gCUdMV0dZOQ4N:-Lmhg8M76RmItzSry6vo:bjd32ks) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L1357)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

The signal handling functionality only works in CK_FORK mode. 
http://check.sourceforge.net/doc/check_html/check_4.html#Testing-Signal-Handling-and-Exit-Values
</blockquote></details>

According to https://libcheck.github.io/check/doc/check_html/check_4.html#No-Fork-Mode
"Check normally forks to create a separate address space"
See:
https://github.com/libcheck/check/blob/285d04b3d461ba68dc39e0f9e847784fb6064bb3/src/check.c#L418
https://github.com/libcheck/check/blob/285d04b3d461ba68dc39e0f9e847784fb6064bb3/src/check_run.c#L734
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 80 at r3](https://reviewable.io/reviews/pmem/pelikan/67#-LmhhCkCCxIC9EGsyISy:-LmhhCkCCxIC9EGsyISz:b-120vq4) ([raw file](https://github.com/pmem/pelikan/blob/c324e37c1e1dac14c8bfa0d6d2795ba793296568/test/storage/slab_pmem/check_slab_pmem.c#L80)):*
> ```
> (pmem_addr)
> ```
remove brackets
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1035 at r3](https://reviewable.io/reviews/pmem/pelikan/67#-LmhfUpD2rar1DxT9Wmc:-LmhfUpD2rar1DxT9Wmd:bu1e3f) ([raw file](https://github.com/pmem/pelikan/blob/c324e37c1e1dac14c8bfa0d6d2795ba793296568/test/storage/slab_pmem/check_slab_pmem.c#L1035)):*
> ```C
> END_TEST
> ```

remove this change
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1331 at r3](https://reviewable.io/reviews/pmem/pelikan/67#-LmhgUK38V68spFEA_54:-LmhgUK38V68spFEA_55:b3dj9cr) ([raw file](https://github.com/pmem/pelikan/blob/c324e37c1e1dac14c8bfa0d6d2795ba793296568/test/storage/slab_pmem/check_slab_pmem.c#L1331)):*
> ```
>     suite_add_tcase(s, tc_item_release);
> ```
nit:
please remove spaces in the beginning


<!-- Sent from Reviewable.io -->

2019-08-23 09:31 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @michalbiesek and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 51 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlB815pmIMtP4LlXf:-LmxaYfp2LJFEueM71d-:b-7rznjp) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L51)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

I am not sure if this allocations is needed you could do this by simple array with constant size.
Regarding the rest of code below I need to think if this could be simplified
</blockquote></details>

As you suspected it can be simplified, thanks for the tip!
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 81 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlQDs49qdnpsUnS28:-LmxarRf6w5PsKQxa0iu:b-xi6tii) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L81)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Nope
</blockquote></details>

Ok, I misunderstood
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 83 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-LmdlSzU0zCUcXthrDKJ:-Lmxcprb1uaXVSFDAIM6:bb6un1j) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L83)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

please use local variable for that since you call it sysconf here twice
</blockquote></details>

Done
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1357 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-Lmdlv0gCUdMV0dZOQ4N:-LmxoCdp5uih8swV9cba:ba3dfob) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L1357)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

According to https://libcheck.github.io/check/doc/check_html/check_4.html#No-Fork-Mode
"Check normally forks to create a separate address space"
See:
https://github.com/libcheck/check/blob/285d04b3d461ba68dc39e0f9e847784fb6064bb3/src/check.c#L577
</blockquote></details>

Removed
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 80 at r3](https://reviewable.io/reviews/pmem/pelikan/67#-LmhhCkCCxIC9EGsyISy:-LmxazR-CrTgBxB_dlFe:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/c324e37c1e1dac14c8bfa0d6d2795ba793296568/test/storage/slab_pmem/check_slab_pmem.c#L80)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> (pmem_addr)
> ```
remove brackets
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1035 at r3](https://reviewable.io/reviews/pmem/pelikan/67#-LmhfUpD2rar1DxT9Wmc:-Lmxd2Ea7uS0MAJlYIc2:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/c324e37c1e1dac14c8bfa0d6d2795ba793296568/test/storage/slab_pmem/check_slab_pmem.c#L1035)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

remove this change
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1331 at r3](https://reviewable.io/reviews/pmem/pelikan/67#-LmhgUK38V68spFEA_54:-Lmxo2DCBXI0Lbe2Ni4U:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/c324e37c1e1dac14c8bfa0d6d2795ba793296568/test/storage/slab_pmem/check_slab_pmem.c#L1331)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     suite_add_tcase(s, tc_item_release);
> ```
nit:
please remove spaces in the beginning
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-23 12:48 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @kasiawasiuta and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1035 at r3](https://reviewable.io/reviews/pmem/pelikan/67#-LmhfUpD2rar1DxT9Wmc:-Lmy9OHp3yADsey8yDXz:bb710yj) ([raw file](https://github.com/pmem/pelikan/blob/c324e37c1e1dac14c8bfa0d6d2795ba793296568/test/storage/slab_pmem/check_slab_pmem.c#L1035)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 68 at r4](https://reviewable.io/reviews/pmem/pelikan/67#-LmyBbeS7riMXGJOc-3X:-LmyBbeS7riMXGJOc-3Y:btikkvk) ([raw file](https://github.com/pmem/pelikan/blob/f8777e7fc668bf68786c6563b012688b489f5b5f/test/storage/slab_pmem/check_slab_pmem.c#L68)):*
> ```
>  test_get_pmem_mapping_start();
> ```
the main issue with this is that you must update tests if you change address by default. 
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 73 at r4](https://reviewable.io/reviews/pmem/pelikan/67#-Lmy9ApE0__S6y4XCdNS:-Lmy9ApE0__S6y4XCdNT:b-me45d6) ([raw file](https://github.com/pmem/pelikan/blob/f8777e7fc668bf68786c6563b012688b489f5b5f/test/storage/slab_pmem/check_slab_pmem.c#L73)):*
> ```
>  PROT_NONE
> ```
nit: remove space before PROT_NONE ( now there are 2 spaces), same before MAP_PRIVATE|MAP_ANONYMOUS
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 955 at r4](https://reviewable.io/reviews/pmem/pelikan/67#-LmyBBnD1envEdzHWFkw:-LmyBBnD1envEdzHWFkx:b-xzn7d3) ([raw file](https://github.com/pmem/pelikan/blob/e84e4c7d328b215961296e5c8ee9dc10897f363e/test/storage/slab_pmem/check_slab_pmem.c#L955)):*
> ```C
>     test_reset(0);
> 
>     ck_assert_msg(s->refcount == 1, "slab refcount %"PRIu32"; 1 expected", s->refcount);
> ```

this depend from changes introduced in #72 - sorry for inconvenience but I prefer to be introduced there - so please remove this change
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1097 at r4](https://reviewable.io/reviews/pmem/pelikan/67#-LmyFW3ZC1NJBHy-UpsF:-LmyFW3ZC1NJBHy-UpsG:b-axh86q) ([raw file](https://github.com/pmem/pelikan/blob/f8777e7fc668bf68786c6563b012688b489f5b5f/test/storage/slab_pmem/check_slab_pmem.c#L1097)):*
> ```
> test_reset_no_addr_change(0)
> ```
I think you want it in this place change address


<!-- Sent from Reviewable.io -->

2019-09-03 09:11 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @kasiawasiuta, @michalbiesek, and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1357 at r2](https://reviewable.io/reviews/pmem/pelikan/67#-Lmdlv0gCUdMV0dZOQ4N:-LmxoG5EDi_-ISaetqH6:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/de79757a4abbe5210b2e0cb16e34bbc41b0c4e0a/test/storage/slab_pmem/check_slab_pmem.c#L1357)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

Removed
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1035 at r3](https://reviewable.io/reviews/pmem/pelikan/67#-LmhfUpD2rar1DxT9Wmc:-LmyaiJY3PqbXYytIJ56:b-78tmxb) ([raw file](https://github.com/pmem/pelikan/blob/c324e37c1e1dac14c8bfa0d6d2795ba793296568/test/storage/slab_pmem/check_slab_pmem.c#L1035)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Nope
</blockquote></details>

Now done
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 73 at r4](https://reviewable.io/reviews/pmem/pelikan/67#-Lmy9ApE0__S6y4XCdNS:-Lmy_FyP7-YvZlrqosy9:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/f8777e7fc668bf68786c6563b012688b489f5b5f/test/storage/slab_pmem/check_slab_pmem.c#L73)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  PROT_NONE
> ```
nit: remove space before PROT_NONE ( now there are 2 spaces), same before MAP_PRIVATE|MAP_ANONYMOUS
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 955 at r4](https://reviewable.io/reviews/pmem/pelikan/67#-LmyBBnD1envEdzHWFkw:-LmybkPC2GAA01WTtW7n:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/e84e4c7d328b215961296e5c8ee9dc10897f363e/test/storage/slab_pmem/check_slab_pmem.c#L955)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

this depend from changes introduced in #72 - sorry for inconvenience but I prefer to be introduced there - so please remove this change
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1097 at r4](https://reviewable.io/reviews/pmem/pelikan/67#-LmyFW3ZC1NJBHy-UpsF:-LnqMRHJ09xHNAfzcWUZ:b6tzr3r) ([raw file](https://github.com/pmem/pelikan/blob/f8777e7fc668bf68786c6563b012688b489f5b5f/test/storage/slab_pmem/check_slab_pmem.c#L1097)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> test_reset_no_addr_change(0)
> ```
I think you want it in this place change address
</blockquote></details>

In version without pmem slab, after restart the slab object is nulled, so there is no need to change the address. How do you want the slab to behave in pmem version?


<!-- Sent from Reviewable.io -->

2019-09-05 06:39 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @kasiawasiuta and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 10 at r5](https://reviewable.io/reviews/pmem/pelikan/67#-Lo-6rep-4FHGusIP9Tf:-Lo-6rep-4FHGusIP9Tg:bp6cxwy) ([raw file](https://github.com/pmem/pelikan/blob/067b8e8cd7134553fd6bf33b19eaa2c9f5ca8314/test/storage/slab_pmem/check_slab_pmem.c#L10)):*
> ```
> #include <signal.h>
> ```
remove
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 82 at r5](https://reviewable.io/reviews/pmem/pelikan/67#-Lo-7Oyw5wKYW_oW6qvj:-Lo-7Oyw5wKYW_oW6qvk:b-33pbzb) ([raw file](https://github.com/pmem/pelikan/blob/067b8e8cd7134553fd6bf33b19eaa2c9f5ca8314/test/storage/slab_pmem/check_slab_pmem.c#L82)):*
> ```
> at the beginning
> ```
this is not related with this PR so make this in another commit
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1071 at r5](https://reviewable.io/reviews/pmem/pelikan/67#-Lo-85693lIUS6A3YRBl:-Lo-856A4cuYQ1nk-O4G:b-eimlyd) ([raw file](https://github.com/pmem/pelikan/blob/067b8e8cd7134553fd6bf33b19eaa2c9f5ca8314/test/storage/slab_pmem/check_slab_pmem.c#L1071)):*
> ```
> when_restarting
> ```
after_restart
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1095 at r5](https://reviewable.io/reviews/pmem/pelikan/67#-Lo-6x2KDgUVKLCDOsZm:-Lo-6x2KDgUVKLCDOsZn:b-jjfl4h) ([raw file](https://github.com/pmem/pelikan/blob/067b8e8cd7134553fd6bf33b19eaa2c9f5ca8314/test/storage/slab_pmem/check_slab_pmem.c#L1095)):*
> ```
> ····
> ```
remove whitespaces after item_to_slab(it)
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1096 at r5](https://reviewable.io/reviews/pmem/pelikan/67#-Lo-7HOmAd3e6haSuedc:-Lo-7HOmAd3e6haSuedd:b-ftfzu2) ([raw file](https://github.com/pmem/pelikan/blob/067b8e8cd7134553fd6bf33b19eaa2c9f5ca8314/test/storage/slab_pmem/check_slab_pmem.c#L1096)):*
> ```
> After restart 0 expected
> ```
"0 expected"
would be enough


<!-- Sent from Reviewable.io -->

2019-09-17 13:22 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @michalbiesek and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 68 at r4](https://reviewable.io/reviews/pmem/pelikan/67#-LmyBbeS7riMXGJOc-3X:-Lnvt-ew4nzjVXE9u3qb:b-is6w5o) ([raw file](https://github.com/pmem/pelikan/blob/f8777e7fc668bf68786c6563b012688b489f5b5f/test/storage/slab_pmem/check_slab_pmem.c#L68)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  test_get_pmem_mapping_start();
> ```
the main issue with this is that you must update tests if you change address by default. 
</blockquote></details>

Please take look at 
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 10 at r5](https://reviewable.io/reviews/pmem/pelikan/67#-Lo-6rep-4FHGusIP9Tf:-LozNeTp1BNFxweIAOJO:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/067b8e8cd7134553fd6bf33b19eaa2c9f5ca8314/test/storage/slab_pmem/check_slab_pmem.c#L10)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> #include <signal.h>
> ```
remove
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 82 at r5](https://reviewable.io/reviews/pmem/pelikan/67#-Lo-7Oyw5wKYW_oW6qvj:-LozNVUR7ZnCv5IadEov:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/067b8e8cd7134553fd6bf33b19eaa2c9f5ca8314/test/storage/slab_pmem/check_slab_pmem.c#L82)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> at the beginning
> ```
this is not related with this PR so make this in another commit
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1071 at r5](https://reviewable.io/reviews/pmem/pelikan/67#-Lo-85693lIUS6A3YRBl:-LozJUdb52ft3aJXENzJ:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/067b8e8cd7134553fd6bf33b19eaa2c9f5ca8314/test/storage/slab_pmem/check_slab_pmem.c#L1071)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> when_restarting
> ```
after_restart
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1095 at r5](https://reviewable.io/reviews/pmem/pelikan/67#-Lo-6x2KDgUVKLCDOsZm:-LozKa-xBgTdpqEreEcb:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/067b8e8cd7134553fd6bf33b19eaa2c9f5ca8314/test/storage/slab_pmem/check_slab_pmem.c#L1095)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ····
> ```
remove whitespaces after item_to_slab(it)
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1096 at r5](https://reviewable.io/reviews/pmem/pelikan/67#-Lo-7HOmAd3e6haSuedc:-LozKCPT3XcQiCDGBSWa:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/067b8e8cd7134553fd6bf33b19eaa2c9f5ca8314/test/storage/slab_pmem/check_slab_pmem.c#L1096)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> After restart 0 expected
> ```
"0 expected"
would be enough
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-18 06:53 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @kasiawasiuta and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1095 at r5](https://reviewable.io/reviews/pmem/pelikan/67#-Lo-6x2KDgUVKLCDOsZm:-Lp27lf81mygBQcarh4I:b-8b6lx5) ([raw file](https://github.com/pmem/pelikan/blob/067b8e8cd7134553fd6bf33b19eaa2c9f5ca8314/test/storage/slab_pmem/check_slab_pmem.c#L1095)):*
> ```
>     test_reset(0);····
> ```
Remove whitespaces from here
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1574 at r6](https://reviewable.io/reviews/pmem/pelikan/67#-Lp27soVERgocq5ta93t:-Lp27soVERgocq5ta93u:bwr2y2v) ([raw file](https://github.com/pmem/pelikan/blob/db98db9ebb9cb9e41969096b6cc74abfdd3f9486/test/storage/slab_pmem/check_slab_pmem.c#L1574)):*
> ```
> test_release_reserved_items_after_restart
> ```
IMHO this is pretty simple test so this could be easily added to already existing tcase pick "slab api" or "item api".


<!-- Sent from Reviewable.io -->

2019-09-18 11:41 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @kasiawasiuta and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1562 at r7](https://reviewable.io/reviews/pmem/pelikan/67#-Lp3AI_AE1cBlaRdS1bj:-Lp3AI_AE1cBlaRdS1bk:b-q2570) ([raw file](https://github.com/pmem/pelikan/blob/09e7d254da8aae10cba43f8240a31aaa4d156fd5/test/storage/slab_pmem/check_slab_pmem.c#L1562)):*
> ```
>  tcase_add_test(tc_item, test_freeq);····
> ```
:)
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1574 at r7](https://reviewable.io/reviews/pmem/pelikan/67#-Lp3ALSD8K6bMPzifsTp:-Lp3ALSD8K6bMPzifsTq:b-6ewpn6) ([raw file](https://github.com/pmem/pelikan/blob/09e7d254da8aae10cba43f8240a31aaa4d156fd5/test/storage/slab_pmem/check_slab_pmem.c#L1574)):*
> ```
> 
>     TCase *tc_item_release = tcase_create("releasing non inserted objects");
>     suite_add_tcase(s, tc_item_release);
> ```
This changes are not needed anymore so please remove


<!-- Sent from Reviewable.io -->

2019-09-18 12:23 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @michalbiesek and @TomekIdczak97)

___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1562 at r7](https://reviewable.io/reviews/pmem/pelikan/67#-Lp3AI_AE1cBlaRdS1bj:-Lp3G6ydBRpNnFYDPloo:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/09e7d254da8aae10cba43f8240a31aaa4d156fd5/test/storage/slab_pmem/check_slab_pmem.c#L1562)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>  tcase_add_test(tc_item, test_freeq);····
> ```
:)
</blockquote></details>

Done.
___
*[test/storage/slab_pmem/check_slab_pmem.c, line 1574 at r7](https://reviewable.io/reviews/pmem/pelikan/67#-Lp3ALSD8K6bMPzifsTp:-Lp3G8HPAYvbYZ9NQwvK:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/09e7d254da8aae10cba43f8240a31aaa4d156fd5/test/storage/slab_pmem/check_slab_pmem.c#L1574)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 
>     TCase *tc_item_release = tcase_create("releasing non inserted objects");
>     suite_add_tcase(s, tc_item_release);
> ```
This changes are not needed anymore so please remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-18 12:27 UTC, michalbiesek approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @TomekIdczak97)



<!-- Sent from Reviewable.io -->

2019-09-18 12:27 UTC, michalbiesek approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: all files reviewed, 1 unresolved discussion (waiting on @TomekIdczak97)



<!-- Sent from Reviewable.io -->

2019-09-18 12:27 UTC, michalbiesek approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/67)* status: all files reviewed, 1 unresolved discussion (waiting on @TomekIdczak97)



<!-- Sent from Reviewable.io -->

2019-09-18 12:28 UTC, merged