integration tests assertion fix
pmem/pelikan pull request #75
Opened 2019-09-13 08:49 UTC by TomekIdczak97

fix for fail assertion of python integration tests.

2019-09-13 09:28 UTC, michalbiesek reviewed
Please change commit message the main reason of this changes is to fix false positive currently generated by integration test. In other words make test result with always Passed test for integration test even if the integration test itself fail.

2019-09-13 12:34 UTC, michalbiesek commented on test/integration/CMakeLists.txt
> +if(USE_PMEM)
nit:
I think this is else could be simplified:
if(USE_PMEM)
    set(test_arg --pmem)
endif()
and use
COMMAND ${PYTHON_EXECUTABLE} test_twemcache.py ${test_arg}

2019-09-13 12:34 UTC, michalbiesek commented on test/integration/test_twemcache.py
> +def twemcache(PmemFlag=False):
nit:
please use small letter "pmem_flag" instead of PmemFlag (this is how it is done in other files here in function definition)

2019-09-16 08:08 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/75)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @TomekIdczak97)

___
*[test/integration/CMakeLists.txt, line 12 at r3](https://reviewable.io/reviews/pmem/pelikan/75#-Losy1i06F0misfhBcW5:-Losy1i06F0misfhBcW6:b-i4280d) ([raw file](https://github.com/pmem/pelikan/blob/083ed0ee2ae9d196fb7d083c1adf4a63794e99e4/test/integration/CMakeLists.txt#L12)):*
> ```CMake
>     COMMAND ${PYTHON_EXECUTABLE} test_twemcache.py ${test_arg}
>     WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
> ```

remove empty new line in the end


<!-- Sent from Reviewable.io -->

2019-09-16 09:11 UTC, michalbiesek requested changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/75)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @TomekIdczak97)

___
*[test/integration/CMakeLists.txt, line 10 at r3](https://reviewable.io/reviews/pmem/pelikan/75#-LotKdkEA33v5oZISiHd:-LotKdkEA33v5oZISiHe:bvxnkon) ([raw file](https://github.com/pmem/pelikan/blob/083ed0ee2ae9d196fb7d083c1adf4a63794e99e4/test/integration/CMakeLists.txt#L10)):*
> ```
>     COMMAND ${PYTHON_EXECUTABLE} test_twemcache.py ${test_arg}
> ```
Please leave original indent here


<!-- Sent from Reviewable.io -->

2019-09-16 11:35 UTC, TomekIdczak97 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/75)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @michalbiesek)

___
*[test/integration/CMakeLists.txt, line 10 at r3](https://reviewable.io/reviews/pmem/pelikan/75#-LotKdkEA33v5oZISiHd:-Lotqez96hGWy27CfJiK:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/083ed0ee2ae9d196fb7d083c1adf4a63794e99e4/test/integration/CMakeLists.txt#L10)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     COMMAND ${PYTHON_EXECUTABLE} test_twemcache.py ${test_arg}
> ```
Please leave original indent here
</blockquote></details>

Done.
___
*[test/integration/CMakeLists.txt, line 12 at r3](https://reviewable.io/reviews/pmem/pelikan/75#-Losy1i06F0misfhBcW5:-LotqfHS0vH6_-gUJPEj:b-896fix) ([raw file](https://github.com/pmem/pelikan/blob/083ed0ee2ae9d196fb7d083c1adf4a63794e99e4/test/integration/CMakeLists.txt#L12)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

remove empty new line in the end
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-16 11:40 UTC, michalbiesek approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pelikan/75)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-16 11:40 UTC, merged